version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: th_crm-web
    volumes:
      - .:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=th_crm
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8
    container_name: th_crm-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=th_crm
    volumes:
      - ./docker/data:/var/lib/mysql
      - ./import_script.sh:/docker-entrypoint-initdb.d/import_script.sh
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: th_crm-phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - db

  mailhog:
    image: mailhog/mailhog
    container_name: th_crm-mailhog
    restart: always
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
